package main

import (
	"log"
	"strconv"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"

	"afeilulu.com/example/config"
	"afeilulu.com/example/database"
	"afeilulu.com/example/router"

	_ "afeilulu.com/example/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title *** API
// @version 1.0
// @description
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @BasePath /
func main() {

	// Connect to database
	database.InitDB()

	fiberPrefork, _ := strconv.ParseBool(config.Config("PREFORK"))
	app := fiber.New(fiber.Config{
		Prefork: fiberPrefork,
	})

	// Default middleware config
	app.Use(logger.New())

	router.SetupRoutes(app)

	log.Fatal(app.Listen(":9090"))

}
